<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="19968" started-at="2022-08-05T15:12:27 IST" finished-at="2022-08-05T15:12:47 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="19968" started-at="2022-08-05T15:12:27 IST" finished-at="2022-08-05T15:12:47 IST">
      <class name="com.obsqura.scripts.TestClass">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.obsqura.scripts.TestClass@aecb35a]" name="setUp" is-config="true" duration-ms="12223" started-at="2022-08-05T15:12:27 IST" finished-at="2022-08-05T15:12:40 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="InvalidLogin3()[pri:0, instance:com.obsqura.scripts.TestClass@aecb35a]" name="InvalidLogin3" duration-ms="0" started-at="2022-08-05T15:12:40 IST" finished-at="2022-08-05T15:12:40 IST">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void com.obsqura.scripts.TestClass.InvalidLogin3() throws java.io.IOException requires a @DataProvider named : pass]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void com.obsqura.scripts.TestClass.InvalidLogin3() throws java.io.IOException requires a @DataProvider named : pass
at org.testng.internal.Parameters.findDataProvider(Parameters.java:561)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidLogin3 -->
        <test-method status="FAIL" signature="InvalidLogin2()[pri:1, instance:com.obsqura.scripts.TestClass@aecb35a]" name="InvalidLogin2" duration-ms="3755" started-at="2022-08-05T15:12:40 IST" finished-at="2022-08-05T15:12:43 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Epic sadface: Password is required] but found [Epic sadface: Password is required1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Epic sadface: Password is required] but found [Epic sadface: Password is required1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.obsqura.scripts.TestClass.InvalidLogin2(TestClass.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidLogin2 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.obsqura.scripts.TestClass@aecb35a]" name="tearDown" is-config="true" duration-ms="2340" started-at="2022-08-05T15:12:43 IST" finished-at="2022-08-05T15:12:46 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=InvalidLogin2 status=FAILURE method=TestClass.InvalidLogin2()[pri:1, instance:com.obsqura.scripts.TestClass@aecb35a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="InvalidLogin1()[pri:2, instance:com.obsqura.scripts.TestClass@aecb35a]" name="InvalidLogin1" duration-ms="862" started-at="2022-08-05T15:12:46 IST" finished-at="2022-08-05T15:12:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- InvalidLogin1 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.obsqura.scripts.TestClass@aecb35a]" name="tearDown" is-config="true" duration-ms="1" started-at="2022-08-05T15:12:47 IST" finished-at="2022-08-05T15:12:47 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=InvalidLogin1 status=SUCCESS method=TestClass.InvalidLogin1()[pri:2, instance:com.obsqura.scripts.TestClass@aecb35a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="verifyLogin()[pri:3, instance:com.obsqura.scripts.TestClass@aecb35a]" name="verifyLogin" duration-ms="704" started-at="2022-08-05T15:12:47 IST" finished-at="2022-08-05T15:12:47 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.obsqura.scripts.TestClass@aecb35a]" name="tearDown" is-config="true" duration-ms="1" started-at="2022-08-05T15:12:47 IST" finished-at="2022-08-05T15:12:47 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLogin status=SUCCESS method=TestClass.verifyLogin()[pri:3, instance:com.obsqura.scripts.TestClass@aecb35a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.obsqura.scripts.TestClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
